[event[0] setEventTime:@"9 am–4 pm"];
[event[0] setEventLocation:@"McDougall Hall 246"];
[event[0] setEventTitle:@"NSO Pack Pick-Up/Registration"];
[event[0] setEventDescription:@"Come and pick up your NSO pack. It has lots of goodies and information inside. Meet the leaders and get your schedule for the week! "];
[event[1] setEventTime:@"4–6 pm "];
[event[1] setEventLocation:@"Residence Floors & McDougall Hall 242"];
[event[1] setEventTitle:@"Residence & non-Residence"];
[event[1] setEventDescription:@"information meetings"];
[event[2] setEventTime:@"6–8 pm "];
[event[2] setEventLocation:@"Meet in the Quadrangle "];
[event[2] setEventTitle:@"Team Meetings & Flag Making "];
[event[2] setEventDescription:@"Meet your teammates and plan how you will win the Game of NSO 2012! "];
[event[3] setEventTime:@"8-10:30pm"];
[event[3] setEventLocation:@"UPEI Turf Field"];
[event[3] setEventTitle:@"NSO 2012 Kick-Off and PlayFair"];
[event[3] setEventDescription:@" "];
[event[4] setEventTime:@"10:30 pm - 12:30 am"];
[event[4] setEventLocation:@"CARI Pool"];
[event[4] setEventTitle:@"POOL Part with DJ Alex"];
[event[4] setEventDescription:@"  "];
[event[5] setEventTime:@"8:30–10 am"];
[event[5] setEventLocation:@"UPEI Chaplaincy Centre"];
[event[5] setEventTitle:@"Chaplaincy Centre Breakfast"];
[event[5] setEventDescription:@"Come enjoy pancakes, sausages, and timespent with friends."];
[event[6] setEventTime:@"10–10:30 am"];
[event[6] setEventLocation:@"Meet in the Quadrangle"];
[event[6] setEventTitle:@"Team Meetings"];
[event[6] setEventDescription:@"Meet with your team to discuss the events forthe day and any questions you may have."];
[event[7] setEventTime:@"10:30 am–12:10 pm"];
[event[7] setEventLocation:@"McDougall Hall"];
[event[7] setEventTitle:@"UPEI 101: Sessions A, B, C, D"];
[event[7] setEventDescription:@""];
[event[8] setEventTime:@"12:10 –12:30 pm"];
[event[8] setEventLocation:@"McDougall Hall"];
[event[8] setEventTitle:@"Team Challenge"];
[event[8] setEventDescription:@"Is your team the fastest, smartest, andthe winners of this team challenge?"];
[event[9] setEventTime:@"12:30–4 pm"];
[event[9] setEventLocation:@"Residence Fields"];
[event[9] setEventTitle:@"NSO 2012 Picnic"];
[event[9] setEventDescription:@"Enjoy subs sponsored by Quiznos, inflatablegames, games, prizes, and more.There will be water games at this event"];
[event[10] setEventTime:@"6 pm"];
[event[10] setEventLocation:@"UPEI Chaplaincy Centre"];
[event[10] setEventTitle:@"Mass"];
[event[10] setEventDescription:@""];
[event[11] setEventTime:@"9 pm–2 am"];
[event[11] setEventLocation:@"W.A. Murphy Student Centre"];
[event[11] setEventTitle:@"Dance Party"];
[event[11] setEventDescription:@"Dance ‘til you drop to the tunes ofDJ Ray Ray and DJ Bagera."];
[event[12] setEventTime:@"9–9:30 am"];
[event[12] setEventLocation:@"Meet in the Quadrangle "];
[event[12] setEventTitle:@"Team Meetings"];
[event[12] setEventDescription:@"Meet with your team to discuss the events for the day and any questions you may have."];
[event[13] setEventTime:@"9:30 am–12 pm"];
[event[13] setEventLocation:@"W.A. Murphy Student Centre"];
[event[13] setEventTitle:@"NSO Scavenger hunt"];
[event[13] setEventDescription:@"Not just a campus tour but a lot of fun as well. "];
[event[14] setEventTime:@"12–1:30 pm  "];
[event[14] setEventLocation:@"W.A. Murphy Student Centre "];
[event[14] setEventTitle:@"BBQ Sponsored By UPEISU"];
[event[14] setEventDescription:@"Meet the UPEISU executive and councillors and have some yummy treats as well. "];
[event[15] setEventTime:@"1:30–3 pm  "];
[event[15] setEventLocation:@"W.A. Murphy Student Centre "];
[event[15] setEventTitle:@"Drew Dudley"];
[event[15] setEventDescription:@"Funny, inspiring, and loves penguins—come listen to the wonderful words of Drew Dudley! "];
[event[16] setEventTime:@"3–3:30 pm  "];
[event[16] setEventLocation:@"W.A. Murphy Student Centre"];
[event[16] setEventTitle:@"Bling Bling! "];
[event[16] setEventDescription:@"How much $$ can your team raise for Shinerama in 30 minutes? You’re about to find out! "];
[event[17] setEventTime:@"3:30–4:30 pm"];
[event[17] setEventLocation:@"McDougall Hall 242 "];
[event[17] setEventTitle:@"UPEI 101: Sessions E & F"];
[event[17] setEventDescription:@""];
[event[18] setEventTime:@"4:30–5:30 pm  "];
[event[18] setEventLocation:@"Webster Centre in the Robertson Library"];
[event[18] setEventTitle:@"Webster Center Welcome! "];
[event[18] setEventDescription:@"Find out what services the Webster Centre offers—plus prizes, food, and games to play."];
[event[19] setEventTime:@"8–11:30 pm  "];
[event[19] setEventLocation:@"The Wave "];
[event[19] setEventTitle:@"Night Of Sounds"];
[event[19] setEventDescription:@"Karaoke and good times"];
[event[20] setEventTime:@"9–9:30 am"];
[event[20] setEventLocation:@"W.A. Murphy Student Centre"];
[event[20] setEventTitle:@"Team Meetings"];
[event[20] setEventDescription:@"Find out where will you be for the day,what will your team be doing, and how will you get to your location? "];
[event[21] setEventTime:@"9:30 am–6:30 pm"];
[event[21] setEventLocation:@"Charlottetown"];
[event[21] setEventTitle:@"Shine Day!"];
[event[21] setEventDescription:@"Raise ALL the money for cystic fibrosis research and treatment. "];
[event[22] setEventTime:@"9–11 pm"];
[event[22] setEventLocation:@"W.A. Murphy Student Centre"];
[event[22] setEventTitle:@"Damien the Hypnotist"];
[event[22] setEventDescription:@"He will amaze you. Donations to Shinerama will be collected at the door "];
[event[23] setEventTime:@"7:30–8 am"];
[event[23] setEventLocation:@"W.A. Murphy Student Centre"];
[event[23] setEventTitle:@"Shine Day Registration"];
[event[23] setEventDescription:@"Get your Shiner Kit & have some breakfast."];
[event[24] setEventTime:@"8-9am"];
[event[24] setEventLocation:@"W.A. Murphy Sudent Centre"];
[event[24] setEventTitle:@"Shine Day Kick-Off"];
[event[24] setEventDescription:@"Discover what Shinerama is all about.Thank you for making a differencein the lives of those with cystic fibrosis!Please wear orange & blue!"];
[event[25] setEventTime:@"4-7pm"];
[event[25] setEventLocation:@"Duffy 135"];
[event[25] setEventTitle:@"Faculty Welcome Ceremonies"];
[event[25] setEventDescription:@"Science"];
[event[26] setEventTime:@"4-7pm"];
[event[26] setEventLocation:@"Main (Faculty Lounge)"];
[event[26] setEventTitle:@"Faculty Welcome Ceremonies"];
[event[26] setEventDescription:@"Arts"];
[event[27] setEventTime:@"4-7pm"];
[event[27] setEventLocation:@"McDougall 242"];
[event[27] setEventTitle:@"Faculty Welcome Ceremonies"];
[event[27] setEventDescription:@"Business"];
[event[28] setEventTime:@"7-7:45pm "];
[event[28] setEventLocation:@"Meet in the Quadrangle"];
[event[28] setEventTitle:@"Team Challenge"];
[event[28] setEventDescription:@"  "];
[event[29] setEventTime:@"8-11pm "];
[event[29] setEventLocation:@"Meet in the Quadrangle"];
[event[29] setEventTitle:@"ManHunt"];
[event[29] setEventDescription:@"  "];
[event[30] setEventTime:@"6–9 pm"];
[event[30] setEventLocation:@"Wanda Wyatt Dining Hall"];
[event[30] setEventTitle:@"NSO Final Banquet"];
[event[30] setEventDescription:@"Time to celebrate the finish of New StudentOrientation 2012 with new and old friends, aswell as faculty & staff. Awards to be given andthe 2012 Shinerama total will be announced."];
[event[31] setEventTime:@"2pm "];
[event[31] setEventLocation:@"UPEI Turf Field"];
[event[31] setEventTitle:@"Panther Home Game Openers"];
[event[31] setEventDescription:@"Women's SoccerCome out and cheer on our Panther athletes!Half-time games to incorporate NSO teams."];
[event[32] setEventTime:@"3pm"];
[event[32] setEventLocation:@"UPEI Turf Field"];
[event[32] setEventTitle:@"Panther Home Game Openers"];
[event[32] setEventDescription:@"Women's RugbyCome out and cheer on our Panther athletes!Half-time games to incorporate NSO teams."];
[event[33] setEventTime:@"4:15pm"];
[event[33] setEventLocation:@"UPEI Turf Field"];
[event[33] setEventTitle:@"Men's Soccer"];
[event[33] setEventDescription:@"Come out and cheer on our Panther athletes!Half-time games to incorporate NSO teams."];
