[event[0] setEventTime:@"ï»¿dayStart"];
[event[0] setEventLocation:@"Saturday"];
[event[0] setEventTitle:@"September 1"];
[event[0] setEventDescription:@"9 amâ€“4 pmMcDougall Hall 246NSO Pack Pick-Up/RegistrationCome and pick up your NSO pack. It has lots of goodies and information inside. Meet theleaders and get your schedule for the week!"];
[event[1] setEventTime:@"4â€“6 pm "];
[event[1] setEventLocation:@"Residence Floors & McDougall Hall 242"];
[event[1] setEventTitle:@"Residence & non-Residence"];
[event[1] setEventDescription:@"information meetings"];
[event[2] setEventTime:@"6â€“8 pm"];
[event[2] setEventLocation:@"Meet in the Quadrangle"];
[event[2] setEventTitle:@"Team Meetings & Flag Making"];
[event[2] setEventDescription:@"Meet your teammates and plan how you willwin the Game of NSO 2012!"];
[event[3] setEventTime:@"8â€“10:30 pm"];
[event[3] setEventLocation:@"UPEI Turf Field"];
[event[3] setEventTitle:@"NSO 2012 Kick-Off and PlayFair"];
[event[3] setEventDescription:@"eventEnd10:30 pmâ€“12:30 amCARI PoolPOOL Party with DJ Alex"];
[event[4] setEventTime:@"8:30â€“10 am"];
[event[4] setEventLocation:@"UPEI Chaplaincy Centre"];
[event[4] setEventTitle:@"Chaplaincy Centre Breakfast"];
[event[4] setEventDescription:@"Come enjoy pancakes, sausages, and timespent with friends."];
[event[5] setEventTime:@"10â€“10:30 am"];
[event[5] setEventLocation:@"Meet in the Quadrangle"];
[event[5] setEventTitle:@"Team Meetings"];
[event[5] setEventDescription:@"Meet with your team to discuss the events forthe day and any questions you may have."];
[event[6] setEventTime:@"10:30 amâ€“12:10 pm"];
[event[6] setEventLocation:@"McDougall Hall"];
[event[6] setEventTitle:@"UPEI 101: Sessions A, B, C, D"];
[event[6] setEventDescription:@"eventEnd12:10 â€“12:30 pmMcDougall HallTeam ChallengeIs your team the fastest, smartest, andthe winners of this team challenge?"];
[event[7] setEventTime:@"12:30â€“4 pm"];
[event[7] setEventLocation:@"Residence Fields"];
[event[7] setEventTitle:@"NSO 2012 Picnic"];
[event[7] setEventDescription:@"Enjoy subs sponsored by Quiznos, inflatablegames, games, prizes, and more.There will be water games at this event"];
[event[8] setEventTime:@"6 pm"];
[event[8] setEventLocation:@"UPEI Chaplaincy Centre"];
[event[8] setEventTitle:@"Mass"];
[event[8] setEventDescription:@""];
[event[9] setEventTime:@"9 pmâ€“2 am"];
[event[9] setEventLocation:@"W.A. Murphy Student Centre"];
[event[9] setEventTitle:@"Dance Party"];
[event[9] setEventDescription:@"Dance â€˜til you drop to the tunes ofDJ Ray Ray and DJ Bagera."];
[event[10] setEventTime:@"9â€“9:30 am"];
[event[10] setEventLocation:@"W.A. Murphy Student Centre"];
[event[10] setEventTitle:@"Team Meetings"];
[event[10] setEventDescription:@"Find out where will you be for the day,what will your team be doing, andhow will you get to your location?"];
[event[11] setEventTime:@"9:30 amâ€“6:30 pm"];
[event[11] setEventLocation:@"Charlottetown"];
[event[11] setEventTitle:@"Shine Day!"];
[event[11] setEventDescription:@"Raise ALL the money for cystic fibrosisresearch and treatment."];
[event[12] setEventTime:@"9â€“11 pm"];
[event[12] setEventLocation:@"W.A. Murphy Student Centre"];
[event[12] setEventTitle:@"Damien the Hypnotist"];
[event[12] setEventDescription:@"He will amaze you.Donations to Shinerama will be collected at the door"];
[event[13] setEventTime:@"7:30â€“8 am"];
[event[13] setEventLocation:@"W.A. Murphy Student Centre"];
[event[13] setEventTitle:@"Shine Day Registration"];
[event[13] setEventDescription:@"Get your Shiner Kit & have some breakfast."];
[event[14] setEventTime:@"8-9am"];
[event[14] setEventLocation:@"W.A. Murphy Sudent Centre"];
[event[14] setEventTitle:@"Shine Day Kick-Off"];
[event[14] setEventDescription:@"Discover what Shinerama is all about.Thank you for making a differencein the lives of those with cystic fibrosis!Please wear orange & blue!"];
[event[15] setEventTime:@"4-7pm"];
[event[15] setEventLocation:@"Duffy 135"];
[event[15] setEventTitle:@"Faculty Welcome Ceremonies"];
[event[15] setEventDescription:@"Science"];
[event[16] setEventTime:@"4-7pm"];
[event[16] setEventLocation:@"Main (Faculty Lounge)"];
[event[16] setEventTitle:@"Faculty Welcome Ceremonies"];
[event[16] setEventDescription:@"Arts"];
[event[17] setEventTime:@"4-7pm"];
[event[17] setEventLocation:@"McDougall 242"];
[event[17] setEventTitle:@"Faculty Welcome Ceremonies"];
[event[17] setEventDescription:@"Business"];
[event[18] setEventTime:@"7-7:45pm "];
[event[18] setEventLocation:@"Meet in the Quadrangle"];
[event[18] setEventTitle:@"Team Challenge"];
[event[18] setEventDescription:@"  "];
[event[19] setEventTime:@"8-11pm "];
[event[19] setEventLocation:@"Meet in the Quadrangle"];
[event[19] setEventTitle:@"ManHunt"];
[event[19] setEventDescription:@"  "];
[event[20] setEventTime:@"6â€“9 pm"];
[event[20] setEventLocation:@"Wanda Wyatt Dining Hall"];
[event[20] setEventTitle:@"NSO Final Banquet"];
[event[20] setEventDescription:@"Time to celebrate the finish of New StudentOrientation 2012 with new and old friends, aswell as faculty & staff. Awards to be given andthe 2012 Shinerama total will be announced."];
[event[21] setEventTime:@"2pm "];
[event[21] setEventLocation:@"UPEI Turf Field"];
[event[21] setEventTitle:@"Panther Home Game Openers"];
[event[21] setEventDescription:@"Women's SoccerCome out and cheer on our Panther athletes!Half-time games to incorporate NSO teams."];
[event[22] setEventTime:@"3pm"];
[event[22] setEventLocation:@"UPEI Turf Field"];
[event[22] setEventTitle:@"Panther Home Game Openers"];
[event[22] setEventDescription:@"Women's RugbyCome out and cheer on our Panther athletes!Half-time games to incorporate NSO teams."];
[event[23] setEventTime:@"4:15pm"];
[event[23] setEventLocation:@"UPEI Turf Field"];
[event[23] setEventTitle:@"Men's Soccer"];
[event[23] setEventDescription:@"Come out and cheer on our Panther athletes!Half-time games to incorporate NSO teams."];
